# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: octosand/ing-worker
  tag: 1.0.2
redis:
  usePassword: false
replicaCount: 1
